/**
 * Strict renderer→main action contract for the Setup Wizard — port of
 * anywhere dsh-plugin-desktop src/setup-wizard-contract.ts parse half +
 * setup-wizard-window.ts parseDesktopSetupWizardAction (MIT).
 *
 * The renderer has no IPC and no Node: it navigates to
 * `marisa-setup://complete?<exact keys>` or `marisa-setup://skip`, and the
 * main process parses the URL with a closed-world schema (exact key set, one
 * value each, strict enums). Anything else is rejected.
 */

export type SetupMode = 'compatibility' | 'advanced'
export type SetupMacosMaterial = 'off' | 'transparent'
export type SetupWindowsMaterial = 'off' | 'mica' | 'acrylic'

export interface SetupNotifications {
  readonly enabled: boolean
  readonly notifyOnTurnCompletion: boolean
  readonly notifyOnTurnFailure: boolean
  readonly notifyOnJobCompletion: boolean
  readonly notifyOnJobFailure: boolean
}

export interface SetupSelection {
  readonly mode: SetupMode
  readonly macosMaterial: SetupMacosMaterial
  readonly windowsMaterial: SetupWindowsMaterial
  readonly notifications: SetupNotifications
}

export type SetupWizardResult =
  | { readonly action: 'complete'; readonly selection: SetupSelection }
  | { readonly action: 'skip' }
  | { readonly action: 'quit' }

export const SETUP_WIZARD_SCHEME = 'marisa-setup:'
export const SETUP_WIZARD_COMPLETE_KEYS = Object.freeze([
  'mode',
  'macosMaterial',
  'windowsMaterial',
  'enabled',
  'notifyOnTurnCompletion',
  'notifyOnTurnFailure',
  'notifyOnJobCompletion',
  'notifyOnJobFailure',
] as const)

const MAX_ACTION_BYTES = 8192

function exactBoolean(value: string | null): boolean | undefined {
  if (value === 'true') return true
  if (value === 'false') return false
  return undefined
}

function exactMode(value: string | null): SetupMode | undefined {
  return value === 'compatibility' || value === 'advanced' ? value : undefined
}

function exactMacosMaterial(value: string | null): SetupMacosMaterial | undefined {
  return value === 'off' || value === 'transparent' ? value : undefined
}

function exactWindowsMaterial(value: string | null): SetupWindowsMaterial | undefined {
  return value === 'off' || value === 'mica' || value === 'acrylic' ? value : undefined
}

/**
 * Parse only a bounded, complete action URL generated by the local Setup
 * document (setup-wizard-window.ts parseDesktopSetupWizardAction semantics).
 */
export function parseSetupWizardAction(href: string): SetupWizardResult | undefined {
  if (new TextEncoder().encode(href).byteLength > MAX_ACTION_BYTES) return undefined
  let url: URL
  try { url = new URL(href) } catch { return undefined }
  if (url.protocol !== SETUP_WIZARD_SCHEME
    || url.username !== '' || url.password !== '' || url.port !== ''
    || url.pathname !== '' || url.hash !== '') return undefined
  const keys = [...url.searchParams.keys()]
  if (url.hostname === 'skip') return keys.length === 0 ? Object.freeze({ action: 'skip' as const }) : undefined
  if (url.hostname !== 'complete') return undefined
  const expected = SETUP_WIZARD_COMPLETE_KEYS as readonly string[]
  if (keys.length !== expected.length
    || keys.some(key => !expected.includes(key))
    || expected.some(key => url.searchParams.getAll(key).length !== 1)) return undefined
  const mode = exactMode(url.searchParams.get('mode'))
  const macosMaterial = exactMacosMaterial(url.searchParams.get('macosMaterial'))
  const windowsMaterial = exactWindowsMaterial(url.searchParams.get('windowsMaterial'))
  const enabled = exactBoolean(url.searchParams.get('enabled'))
  const notifyOnTurnCompletion = exactBoolean(url.searchParams.get('notifyOnTurnCompletion'))
  const notifyOnTurnFailure = exactBoolean(url.searchParams.get('notifyOnTurnFailure'))
  const notifyOnJobCompletion = exactBoolean(url.searchParams.get('notifyOnJobCompletion'))
  const notifyOnJobFailure = exactBoolean(url.searchParams.get('notifyOnJobFailure'))
  if (mode === undefined || macosMaterial === undefined || windowsMaterial === undefined
    || enabled === undefined || notifyOnTurnCompletion === undefined
    || notifyOnTurnFailure === undefined || notifyOnJobCompletion === undefined
    || notifyOnJobFailure === undefined) return undefined
  const selection: SetupSelection = Object.freeze({
    mode,
    macosMaterial,
    windowsMaterial,
    notifications: Object.freeze({
      enabled,
      notifyOnTurnCompletion,
      notifyOnTurnFailure,
      notifyOnJobCompletion,
      notifyOnJobFailure,
    }),
  })
  return Object.freeze({ action: 'complete' as const, selection })
}
