#!/usr/bin/env bash
# make-bundle.sh — stage the standalone backend bundle on Linux and tar.zst it
# into desktop/bundle/backend.tar.zst (consumed by go:embed with -tags
# embeddedbundle). Linux port of make-bundle.ps1; semantics are kept 1:1
# except the platform direction of native-binary pruning (keep linux-x64,
# prune win32/darwin) and launcher.sh replacing launcher.cmd.
#
# Bundle layout (archive root = extraction dir):
#   VERSION                       version marker (version-gates re-extraction)
#   node                          bundled Node runtime (exec bit set)
#   mnemon                        memory-engine binary the dsh-mnemon plugin
#                                 spawns via PATH (exec bit set)
#   launcher.sh                   backend launcher the shell spawns (exec bit)
#   LINKS.json                    symlink manifest {link,target} pairs,
#                                 stage-relative forward slashes; recreated by
#                                 the Go extractor as symlinks on extraction
#   marisa-distro/node_modules    hoisted runtime store (real files)
#   marisa-distro/harness         harness body + built libs/dist (BUILT CLI)
#   marisa-distro/plugins|bundles|patches|profiles/marisa/runtime
#   marisa-distro/dsh-mygo        vendored MyGO market (full body)
#   marisa-distro/dsh-skill-manager (full body incl its node_modules)
#   .dsh/profiles/marisa          release profile files (+settings.yaml seed)
#   .dsh/settings.yaml            upstream welcome-notice acknowledgement
#
# Preconditions (NOT run here — same as the Windows script):
#   1. repo root `pnpm install` done          2. harness built (apps/cli/lib)
#   3. compiled plugins ship lib/             4. profile materialized at
#      ~/.dsh/profiles/marisa (generate-profile.mjs + install)
#
# Usage:
#   desktop/bundle/make-bundle.sh [--skip-bodies] [--profile DIR]
#       [--node-bin FILE | --system-node] [--mnemon-bin FILE] [--version X]
#
# Env overrides: NODE_BIN, MNEMON_BIN, MARISA_PROFILE
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
stage="$repo/release/_stage-linux"
out="$repo/desktop/bundle/backend.tar.zst"
cacheDir="$repo/release/.cache"
profile="${MARISA_PROFILE:-$HOME/.dsh/profiles/marisa}"
nodeBinArg="${NODE_BIN:-}"
mnemonBinArg="${MNEMON_BIN:-}"
versionOverride=""
skipBodies=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-bodies) skipBodies=1 ;;
    --profile) profile=$2; shift ;;
    --profile=*) profile=${1#*=} ;;
    --node-bin) nodeBinArg=$2; shift ;;
    --node-bin=*) nodeBinArg=${1#*=} ;;
    --mnemon-bin) mnemonBinArg=$2; shift ;;
    --mnemon-bin=*) mnemonBinArg=${1#*=} ;;
    --system-node) nodeBinArg="__SYSTEM__" ;;
    --version) versionOverride=$2; shift ;;
    --version=*) versionOverride=${1#*=} ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
  shift
done

die() { echo "FATAL: $*" >&2; exit 1; }
log() { printf '==> %s\n' "$*"; }
sizeOf() { du -sb "$1" 2>/dev/null | cut -f1 || echo 0; }

for tool in node pnpm git go tar find readlink; do
  command -v "$tool" >/dev/null || die "required tool not found: $tool"
done

# --- precondition gate: all staging sources must exist --------------------------
# Fail up-front with an actionable list instead of a confusing mid-stage error.
# The release runtime profile (profiles/marisa/runtime) is a gitignored
# in-repo workspace member generated by:
#   MARISA_PROFILE_DIR=profiles/marisa/runtime node profiles/marisa/generate-profile.mjs
# build.sh --bundle generates it automatically; standalone make-bundle.sh users
# must run that command first (or pass --profile pointing at a generated dir).
if (( ! skipBodies )); then
  missing=0
  check_src() { [[ -e "$1" ]] || { echo "  MISSING: $2" >&2; missing=1; }; }
  check_src "$repo/harness" 'harness source tree'
  check_src "$repo/harness/apps/cli/lib/bin.js" 'harness built CLI (run build.sh without --skip-harness-build)'
  check_src "$repo/plugins" 'plugins source tree'
  check_src "$repo/bundles" 'bundles source tree'
  check_src "$repo/patches" 'patches directory'
  check_src "$repo/dsh-mygo" 'dsh-mygo vendored tree'
  check_src "$repo/dsh-skill-manager" 'dsh-skill-manager tree'
  check_src "$repo/profiles/marisa/runtime" 'release runtime profile (build.sh --bundle generates it; standalone: MARISA_PROFILE_DIR=profiles/marisa/runtime node profiles/marisa/generate-profile.mjs)'
  check_src "$profile" "profile dir (--profile-path / MARISA_PROFILE_DIR; default ~/.dsh/profiles/marisa)"
  (( missing == 0 )) || die 'one or more staging sources are missing — run build.sh steps 2-5 first (or build.sh --bundle which generates the runtime profile automatically)'
fi

# registry.npmjs.org resilience (mirrors build.ps1 / make-bundle.ps1 tuning).
export npm_config_fetch_retries='8'
export npm_config_fetch_retry_mintimeout='2000'
export npm_config_fetch_retry_maxtimeout='120000'
export npm_config_network_concurrency='4'

bundleVersion=${versionOverride:-$(node -p "require('$repo/package.json').version")}
[[ $bundleVersion =~ ^[0-9]+\.[0-9]+\.[0-9]+([-._][0-9A-Za-z.-]+)?$ ]] \
  || die "invalid bundle version: $bundleVersion"

# --- runtime layer cache -------------------------------------------------------
# Keyed on pnpm-lock.yaml content + whole-workspace git TREE hash (dirty state
# included via stash create -u). VERSION carries no git sha on purpose so the
# extractor's version gate stays stable across cached rebuilds.
lockHash=$(sha256sum "$repo/pnpm-lock.yaml" | cut -c1-16)
stashCommit=$(git -C "$repo" stash create -u 2>/dev/null || true)
[[ -n $stashCommit ]] || stashCommit=$(git -C "$repo" rev-parse HEAD 2>/dev/null || true)
headHash=$(git -C "$repo" rev-parse HEAD 2>/dev/null || true)
dirtySuffix=''
if [[ -n $stashCommit && $stashCommit != "$headHash" ]]; then dirtySuffix='-dirty'; fi
treeHash=$(git -C "$repo" rev-parse "${stashCommit}^{tree}" 2>/dev/null || true)
[[ -n $treeHash ]] || die "cannot resolve workspace content tree hash"
runtimeKey="$lockHash-${treeHash:0:12}"
cachedOut="$cacheDir/backend-$runtimeKey.tar.zst"

if (( ! skipBodies )) && [[ -f $cachedOut ]]; then
  log "runtime cache HIT: $cachedOut"
  mkdir -p "$(dirname "$out")"
  cp -f "$cachedOut" "$out"
  log "bundle written from cache: $(wc -c <"$out") bytes"
  exit 0
fi

# --- clean + skeleton ----------------------------------------------------------
if (( ! skipBodies )); then rm -rf "$stage" "$out"; fi
mkdir -p "$stage/marisa-distro" "$stage/.dsh/profiles"

extract_tarball_file() { # <tarball> <inner-glob> <dest-file>
  local ball=$1 glob=$2 dest=$3 tmp
  tmp=$(mktemp -d)
  tar -xf "$ball" -C "$tmp" $glob 2>/dev/null || tar -xf "$ball" -C "$tmp"
  local hit
  hit=$(find "$tmp" -type f \( -name "$glob" -o -path "*$glob" \) -perm /111 | head -1)
  [[ -n $hit ]] || hit=$(find "$tmp" -type f -name "$glob" | head -1)
  [[ -n $hit ]] || { rm -rf "$tmp"; die "no '$glob' inside $ball"; }
  cp -f "$hit" "$dest" && chmod 755 "$dest"
  rm -rf "$tmp"
}

if (( ! skipBodies )); then
  printf 'marisa-backend-%s%s' "$bundleVersion" "$dirtySuffix" > "$stage/VERSION"

  # bundled node: explicit bin > official Downloads tarball > system node
  downloads="$HOME/Downloads"
  if [[ -z $nodeBinArg ]]; then
    if compgen -G "$downloads"/node-*-linux-x64.tar.xz >/dev/null; then
      nodeBinArg=$(compgen -G "$downloads"/node-*-linux-x64.tar.xz | sort -V | tail -1)
    elif command -v node >/dev/null; then
      nodeBinArg=$(readlink -f "$(command -v node)")
    fi
  fi
  [[ $nodeBinArg == "__SYSTEM__" ]] && nodeBinArg=$(readlink -f "$(command -v node)")
  if [[ -n ${nodeBinArg:-} && $nodeBinArg == *.tar.* && -f $nodeBinArg ]]; then
    extract_tarball_file "$nodeBinArg" 'node' "$stage/node"
  elif [[ -n $nodeBinArg && $nodeBinArg != __SYSTEM__ && -f $nodeBinArg ]]; then
    cp -f "$nodeBinArg" "$stage/node"
  else
    die "no node runtime found (use --node-bin or place node-v*-linux-x64.tar.xz in ~/Downloads)"
  fi
  chmod 755 "$stage/node"

  # mnemon engine: dsh-mnemon spawns `mnemon` via PATH; launcher prepends root.
  mnemonSrc=$mnemonBinArg
  if [[ -z $mnemonSrc ]]; then
    if compgen -G "$downloads"/mnemon_*_linux_*.tar.gz >/dev/null; then
      mnemonSrc=$(compgen -G "$downloads"/mnemon_*_linux_*.tar.gz | sort -V | tail -1)
    fi
  fi
  if [[ -n $mnemonSrc && -f $mnemonSrc ]]; then
    if [[ $mnemonSrc == *.tar.gz || $mnemonSrc == *.tgz ]]; then
      extract_tarball_file "$mnemonSrc" 'mnemon*' "$stage/mnemon"
    else
      cp -f "$mnemonSrc" "$stage/mnemon" && chmod 755 "$stage/mnemon"
    fi
  else
    die "mnemon binary not found (use --mnemon-bin or place mnemon_*_linux_*.tar.gz in ~/Downloads)"
  fi
  chmod 755 "$stage/mnemon"

  # launcher.sh must stay LF; sh has no cmd.exe CRLF quirk but keep it clean.
  cp -f "$repo/desktop/bundle/launcher.sh" "$stage/launcher.sh"
  chmod 755 "$stage/launcher.sh"
fi

# copy_tree SRC DST [exclude-name...] — dereference symlinks (cp -L semantics),
# exclude ANY path component named EXCLUDE (robocopy /XD parity), preserve mode.
copy_tree() {
  local src=$1 dst=$2; shift 2
  mkdir -p "$dst"
  local excludes=()
  local e
  for e in "$@"; do excludes+=(--exclude="$e"); done
  tar -C "$src" -chf - "${excludes[@]}" . | tar -C "$dst" -xf -
}

if (( ! skipBodies )); then
  log 'staging workspace files ...'
  cp -f "$repo/package.json" "$repo/pnpm-lock.yaml" "$repo/pnpm-workspace.yaml" \
    "$stage/marisa-distro/"
  log 'copying harness body (all node_modules excluded; nested workspace/lock files excluded) ...'
  copy_tree "$repo/harness" "$stage/marisa-distro/harness" node_modules pnpm-workspace.yaml pnpm-lock.yaml
  log 'copying plugins / bundles bodies ...'
  copy_tree "$repo/plugins" "$stage/marisa-distro/plugins" node_modules
  copy_tree "$repo/bundles" "$stage/marisa-distro/bundles" node_modules
  log 'copying release profile workspace member ...'
  copy_tree "$repo/profiles/marisa/runtime" "$stage/marisa-distro/profiles/marisa/runtime" node_modules
  log 'copying patches and vendored bodies ...'
  copy_tree "$repo/patches" "$stage/marisa-distro/patches"
  copy_tree "$repo/dsh-skill-manager" "$stage/marisa-distro/dsh-skill-manager"
  copy_tree "$repo/dsh-mygo" "$stage/marisa-distro/dsh-mygo" node_modules
  log 'copying profile files ...'
  copy_tree "$profile" "$stage/.dsh/profiles/marisa" node_modules

  # Seed DSH home: acknowledge the upstream welcome notice shipped by this
  # bundle's harness (rc7 location: ui-settings-models/src/onboarding-copy.ts).
  local_onboarding="$stage/marisa-distro/harness/packages/client/ui-settings-models/src/onboarding-copy.ts"
  noticeVer=$(sed -n "s/^export const WELCOME_NOTICE_VERSION = '\([^']*\)'.*\$/\1/p" "$local_onboarding")
  [[ -n $noticeVer ]] || die "cannot determine WELCOME_NOTICE_VERSION from $local_onboarding"
  printf "# Marisa acknowledges the upstream internal-test notice for its bundled home.\nui-onboarding:\n  welcomeNoticeVersion: '%s'\n" \
    "$noticeVer" > "$stage/.dsh/settings.yaml"

  # --- single production install (store-cached) -------------------------------
  log 'pnpm install --prod at staged workspace root ...'
  (cd "$stage/marisa-distro" \
    && pnpm install --prod --ignore-scripts --offline --frozen-lockfile) \
    || (log 'offline install failed — retrying online ...' \
        && cd "$stage/marisa-distro" \
        && pnpm install --prod --ignore-scripts --frozen-lockfile)

  # --- node-pty prebuilt binary (skipped by --ignore-scripts) ---------------
  # --ignore-scripts skips node-pty's install script (node scripts/prebuild.js)
  # which downloads pty.node. Without it, prebuilds/linux-x64/ is empty and
  # dsh-subprocess-local crashes at runtime with "Cannot find module pty.node".
  # Copy the prebuilt binary from the live repo's pnpm store (the harness
  # install ran without --ignore-scripts and has it).
  livePtyNode=$(find "$repo/harness/node_modules/.pnpm" \
    -path '*/node-pty/prebuilds/linux-x64/pty.node' 2>/dev/null | head -1)
  if [[ -n $livePtyNode && -f $livePtyNode ]]; then
    stagedPtyDir="$stage/marisa-distro/node_modules/node-pty/prebuilds/linux-x64"
    mkdir -p "$stagedPtyDir"
    cp -f "$livePtyNode" "$stagedPtyDir/pty.node"
    log "copied node-pty prebuilt binary from live repo"
  else
    log "WARNING: node-pty prebuilt binary not found in live repo; terminal may not work"
  fi

  # --- flatten: delete non-root node_modules IMMEDIATELY ----------------------
  # pnpm's hoisted linker creates deeply nested REAL dirs for circular peer
  # deps (cordis ↔ cordis-plugin-loader) that exceed PATH_MAX. These must
  # be removed BEFORE any tree traversal (dedup, link recording) to prevent
  # ENAMETOOLONG / tar EOF errors. Node resolves up the tree to the root
  # marisa-distro/node_modules, so member-internal copies are redundant.
  # Root node_modules symlinks (workspace deps) are PRESERVED here — the
  # link recording phase handles them later.
  #
  # CRITICAL: use -prune (NOT -depth). -depth means "process contents before
  # the dir itself" — find descends INTO the circular chain and hits
  # ENAMETOOLONG before it can delete anything. -prune means "do not descend"
  # — find matches the node_modules dir itself, skips its contents, and
  # rm -rf (GNU coreutils, FTS_PHYS no-follow) unlinks symlinks without
  # following them, breaking the chain trivially.
  # --- shared link recording (used by harness re-link + dedupe phases) -------
  LINKS_TSV=$(mktemp)
  record_link() { printf '%s\t%s\n' "$1" "$2" >> "$LINKS_TSV"; }

  rootNm="$stage/marisa-distro/node_modules"
  find "$stage" -type d -name node_modules ! -path "$rootNm" \
    -prune -exec rm -rf {} + 2>/dev/null || true
  log 'flattened: non-root node_modules deleted post-install'

  # --- re-link harness workspace packages into root node_modules -------------
  # The flatten step above deletes harness/node_modules, which was the ONLY
  # resolution path for harness-internal workspace packages that are NOT
  # hoisted to the root (e.g. dsh-client-ui-renderer, dsh-file-reference-local,
  # dsh-client-ui-brand-official, dsh-client-ui-reference). Without these
  # links the backend boots into rescue mode with ERR_MODULE_NOT_FOUND.
  # Walk every harness workspace member, read its package.json name, and
  # create a symlink in root node_modules if missing.
  log 're-linking harness workspace packages into root node_modules ...'
  hwsCount=0
  for hpkg in "$stage/marisa-distro/harness/packages"/*/*/package.json \
              "$stage/marisa-distro/harness/packages"/*/*/*/package.json; do
    [[ -f $hpkg ]] || continue
    hname=$(node -p "try{require('$hpkg').name||''}catch{''}" 2>/dev/null)
    [[ -n $hname ]] || continue
    # Skip packages already linked in root node_modules
    [[ -e "$rootNm/$hname" || -L "$rootNm/$hname" ]] && continue
    # Target is the package directory (parent of package.json)
    hdir=$(dirname "$hpkg")
    hrel=${hdir#"$stage/"}

    # Create the symlink and record it for LINKS.json
    mkdir -p "$(dirname "$rootNm/$hname")"
    ln -s "$hdir" "$rootNm/$hname"
    record_link "marisa-distro/node_modules/$hname" "$hrel"
    hwsCount=$((hwsCount+1))
  done
  # Also handle harness/apps/* and harness/vendor/* workspace members
  for hpkg in "$stage/marisa-distro/harness/apps"/*/package.json \
              "$stage/marisa-distro/harness/vendor"/*/package.json; do
    [[ -f $hpkg ]] || continue
    hname=$(node -p "try{require('$hpkg').name||''}catch{''}" 2>/dev/null)
    [[ -n $hname ]] || continue
    [[ -e "$rootNm/$hname" || -L "$rootNm/$hname" ]] && continue
    hdir=$(dirname "$hpkg")
    hrel=${hdir#"$stage/"}
    mkdir -p "$(dirname "$rootNm/$hname")"
    ln -s "$hdir" "$rootNm/$hname"
    record_link "marisa-distro/node_modules/$hname" "$hrel"
    hwsCount=$((hwsCount+1))
  done
  log "  re-linked $hwsCount harness workspace packages"

  # --- dedupe file: dependency copies -> symlinks (recorded later) ------------
  log 'deduping file: plugin copies ...'
  dedupeBytes=0; dedupeCount=0
  replace_with_link() { # <stage-abs-real-dir> <link-stage-rel> <target-stage-rel>
    local abs=$1 linkRel=$2 targetRel=$3 sz
    sz=$(sizeOf "$abs"); rm -rf "$abs"
    ln -s "$stage/$targetRel" "$abs"
    record_link "$linkRel" "$targetRel"
    dedupeBytes=$((dedupeBytes+sz)); dedupeCount=$((dedupeCount+1))
  }
  pkg_name_of() { node -p "try{require('$1/package.json').name||''}catch{''}" 2>/dev/null; }

  for pdir in "$stage/marisa-distro/plugins"/*/; do
    pdir=${pdir%/}
    [[ -f $pdir/package.json ]] || continue
    pname=$(pkg_name_of "$pdir") || continue
    [[ -n $pname ]] || continue
    rootPkg="$stage/marisa-distro/node_modules/$pname"
    if [[ -d $rootPkg && ! -L $rootPkg ]]; then
      replace_with_link "$rootPkg" "marisa-distro/node_modules/$pname" \
        "marisa-distro/plugins/${pdir#$stage/marisa-distro/plugins/}"
    fi
  done

  mygo_map=(
    '@r05en1cu/dsh-mygo=marisa-distro/dsh-mygo/packages/cordis/mygo'
    '@r05en1cu/dsh-mygo-api=marisa-distro/dsh-mygo/packages/core/mygo-api'
    '@r05en1cu/dsh-mygo-cli=marisa-distro/dsh-mygo/packages/cordis/mygo-cli'
    '@r05en1cu/dsh-mygo-ext-fabric=marisa-distro/dsh-mygo/packages/extensions/mygo-fabric'
    '@r05en1cu/dsh-mygo-ext-panel=marisa-distro/dsh-mygo/packages/extensions/mygo-panel'
    '@r05en1cu/dsh-mygo-loader-hub=marisa-distro/dsh-mygo/packages/loaders/mygo-loader-hub'
    '@r05en1cu/dsh-mygo-loader-profile=marisa-distro/dsh-mygo/packages/loaders/mygo-loader-profile'
  )
  for entry in "${mygo_map[@]}"; do
    pkgName=${entry%%=*}; targetRel=${entry#*=}
    rootPkg="$stage/marisa-distro/node_modules/$pkgName"
    if [[ -d $rootPkg && ! -L $rootPkg ]]; then
      replace_with_link "$rootPkg" "marisa-distro/node_modules/$pkgName" "$targetRel"
    fi
  done

  bundleNm="$stage/marisa-distro/bundles/marisa-bundle/node_modules"
  if [[ -d $bundleNm ]]; then
    while IFS= read -r bpkg; do
      [[ -d $bpkg && ! -L $bpkg ]] || continue
      pkgRel=${bpkg#"$bundleNm/"}
      rootPkg="$stage/marisa-distro/node_modules/$pkgRel"
      [[ -f $rootPkg/package.json ]] || continue
      targetRel="marisa-distro/node_modules/$pkgRel"
      if [[ -L $rootPkg ]]; then
        resolved=$(readlink -f "$rootPkg" || true)
        case $resolved in
          "$stage"/*) targetRel=${resolved#"$stage/"} ;;
        esac
      fi
      replace_with_link "$bpkg" "marisa-distro/bundles/marisa-bundle/node_modules/$pkgRel" "$targetRel"
    done < <(find "$bundleNm" -mindepth 1 -maxdepth 2 -type d ! -name '.bin' \
              ! -path "$bundleNm/@*/*/*" )
  fi
  log "deduped $dedupeCount copies ($((dedupeBytes/1024/1024)) MB)"
fi

# --- prune dead weight ---------------------------------------------------------
if (( ! skipBodies )); then
  log 'pruning dead weight ...'
  prunedTotal=0
  prune_rel() { # path under stage → delete with size log
    local p="$stage/$1"
    if [[ -e $p || -L $p ]]; then
      local sz; sz=$(sizeOf "$p"); rm -rf "$p"
      prunedTotal=$((prunedTotal+sz))
      echo "  pruned $1 ($sz bytes)"
    fi
  }
  for rel in \
    'marisa-distro/node_modules/@openai' \
    'marisa-distro/node_modules/@anthropic-ai/claude-agent-sdk' \
    'marisa-distro/node_modules/@anthropic-ai/claude-agent-sdk-linux-x64' \
    'marisa-distro/node_modules/@anthropic-ai/claude-agent-sdk-win32-x64' \
    'marisa-distro/node_modules/@anthropic-ai/sdk' \
    'marisa-distro/node_modules/@mistralai' \
    'marisa-distro/node_modules/mermaid' \
    'marisa-distro/node_modules/three' \
    'marisa-distro/node_modules/echarts' \
    'marisa-distro/node_modules/@univerjs' \
    'marisa-distro/node_modules/@univerjs-pro' \
    'marisa-distro/node_modules/@codemirror' \
    'marisa-distro/node_modules/@aiden0z' \
    'marisa-distro/node_modules/xterm' \
    'marisa-distro/node_modules/@xterm'; do
    prune_rel "$rel"
  done

  # PLATFORM REVERSAL vs Windows: keep linux-x64 prebuilds only.
  pb="$stage/marisa-distro/node_modules/node-pty/prebuilds"
  if [[ -d $pb ]]; then
    for d in "$pb"/*/; do
      base=$(basename "$d")
      if [[ $base != linux-x64* ]]; then
        sz=$(sizeOf "$d"); rm -rf "$d"; prunedTotal=$((prunedTotal+sz))
        echo "  pruned node-pty/prebuilds/$base ($sz bytes)"
      fi
    done
  fi
  for scope in '@img' '@esbuild'; do
    sd="$stage/marisa-distro/node_modules/$scope"
    [[ -d $sd ]] || continue
    while IFS= read -r d; do
      base=$(basename "$d")
      sz=$(sizeOf "$d"); rm -rf "$d"; prunedTotal=$((prunedTotal+sz))
      echo "  pruned $scope/$base ($sz bytes)"
    done < <(find "$sd" -mindepth 1 -maxdepth 1 -type d \
              | grep -E '/(sharp-libvips|sharp-linux|esbuild)-' \
              | grep -Ev 'linux-x64$' || true)
  done

  # dev-only packages inside the pnpm virtual store (any member store root).
  store_kill_exact=(
    '@openai+codex' '@anthropic-ai+claude-agent-sdk'
    '@anthropic-ai+claude-agent-sdk-linux-x64'
    '@anthropic-ai+claude-agent-sdk-win32-x64' '@anthropic-ai+sdk'
    '@mistralai+mistralai' typescript rolldown tsdown oxlint oxlint-tsgolint
    esbuild rollup playwright playwright-core mermaid lefthook lightningcss
    shiki '@shikijs+core' '@shikijs+langs' eslint eslint-plugin-sonarjs vitest
    tsx knip publint vite vitepress jsdom prettier
  )
  store_kill_prefix=(
    '@types+' '@vitest+' '@eslint+' '@algolia+' '@openai+' '@anthropic-ai+'
    '@rolldown+binding-' '@oxlint+binding-' '@oxlint-tsgolint+'
    '@esbuild+' 'lefthook-' 'lightningcss-'
  )
  log 'pruning dev-only packages from the pnpm virtual store ...'
  for storeRoot in \
    "$stage/marisa-distro/harness/node_modules/.pnpm" \
    "$stage/marisa-distro/node_modules/.pnpm" \
    "$stage/.dsh/profiles/marisa/node_modules/.pnpm"; do
    [[ -d $storeRoot ]] || continue
    while IFS= read -r entry; do
      ename=$(basename "$entry")
      pkgKey=$(printf '%s' "$ename" | sed -E 's/^(@[^@]+\+[^@]+|[^@]+)@.*/\1/')
      [[ -n $pkgKey && $pkgKey != "$ename" ]] || continue
      kill=0
      for k in "${store_kill_exact[@]}"; do [[ $pkgKey == "$k" ]] && kill=1 && break; done
      if (( ! kill )); then
        for k in "${store_kill_prefix[@]}"; do [[ $pkgKey == "$k"* ]] && kill=1 && break; done
      fi
      (( kill )) || continue
      sz=$(sizeOf "$entry"); rm -rf "$entry"; prunedTotal=$((prunedTotal+sz))
      echo "  pruned store $ename ($sz bytes)"
    done < <(find "$storeRoot" -mindepth 1 -maxdepth 1 -type d)
  done

  # hoisted top-level dev-only packages (typescript KEPT: dsh-code-map loads
  # the TS compiler at runtime).
  log 'pruning hoisted dev-only root packages ...'
  hoistedKill=(tsx vite vitest jsdom rollup @rollup @esbuild @shikijs
    lightningcss lightningcss-win32-x64-msvc lightningcss-linux-x64-gnu @vitest
    prettier eslint @eslint playwright playwright-core mermaid vitepress knip
    publint tsdown rolldown oxlint)
  nmRoot="$stage/marisa-distro/node_modules"
  for name in "${hoistedKill[@]}"; do
    [[ -e "$nmRoot/$name" || -L "$nmRoot/$name" ]] || continue
    sz=$(sizeOf "$nmRoot/$name"); rm -rf "$nmRoot/$name"; prunedTotal=$((prunedTotal+sz))
    echo "  pruned hoisted $name ($sz bytes)"
  done
  if [[ -d "$nmRoot/@types" ]]; then
    sz=$(sizeOf "$nmRoot/@types"); rm -rf "$nmRoot/@types"; prunedTotal=$((prunedTotal+sz))
    echo "  pruned hoisted @types ($sz bytes)"
  fi
  log "total pruned: $((prunedTotal/1024/1024)) MB"

  # --- staged tree integrity check --------------------------------------------
  log 'verifying staged tree integrity ...'
  bad=0; badSample=''
  while IFS= read -r d; do
    base=$(basename "$d")
    case $base in .*) continue ;; esac
    if [[ ! -f $d/package.json ]]; then
      if [[ $base == @* ]]; then
        while IFS= read -r sub; do
          [[ -f $sub/package.json ]] || { bad=$((bad+1)); badSample="$badSample @$base/$(basename "$sub"),"; }
        done < <(find "$d" -mindepth 1 -maxdepth 1 -type d)
      else
        bad=$((bad+1)); badSample="$badSample $base,"
      fi
    fi
  done < <(find "$nmRoot" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)
  for mglob in 'plugins/*' 'bundles/*' 'harness/packages/*/*' 'harness/vendor/*' 'harness/apps/*'; do
    while IFS= read -r d; do
      [[ -d $d && ! -f $d/package.json ]] && { bad=$((bad+1)); badSample="$badSample ${d#"$stage"/},"; }
    done < <(compgen -G "$stage/marisa-distro/${mglob}" 2>/dev/null || true)
  done
  (( bad == 0 )) || die "staged tree INCOMPLETE — $bad entries missing package.json:${badSample%, }"

  required_pkgs=(
    '@deepseek-ai/schemastery' '@deepseek-ai/dsh-workflow'
    '@deepseek-ai/dsh-host-webserver' '@deepseek-ai/dsh-host-apiproxy'
    '@deepseek-ai/dsh-client-runtime' '@deepseek-ai/dsh-client-connection'
    '@deepseek-ai/dsh-client-ui-slots' '@deepseek-ai/dsh-client-locale'
    '@deepseek-ai/dsh-session-persistence' '@deepseek-ai/dsh-credentials'
    '@r05en1cu/dsh-mygo' '@r05en1cu/dsh-mygo-loader-hub'
    '@r05en1cu/dsh-mygo-cli' '@r05en1cu/dsh-mygo-ext-panel'
  )
  for rp in "${required_pkgs[@]}"; do
    [[ -f "$nmRoot/$rp/package.json" ]] \
      || die "staged tree INCOMPLETE — required root runtime package missing: $rp"
  done
  log '  staged tree integrity OK'
fi

# --- symlink walker + ALL-staged link recording ---------------------------------
LINKS_TSV=${LINKS_TSV:-$(mktemp)}
touch "$LINKS_TSV"
record_link() { printf '%s\t%s\n' "$1" "$2" >> "$LINKS_TSV"; }

map_live_to_stage() { # live repo path -> stage-relative, empty when unmappable
  local p=$1
  case $p in
    "$repo/node_modules"|"$repo/node_modules"/*) echo "marisa-distro/node_modules${p#"$repo/node_modules"}" ;;
    "$repo/harness"|"$repo/harness"/*)          echo "marisa-distro/harness${p#"$repo/harness"}" ;;
    "$repo/plugins"|"$repo/plugins"/*)          echo "marisa-distro/plugins${p#"$repo/plugins"}" ;;
    "$repo/bundles"|"$repo/bundles"/*)          echo "marisa-distro/bundles${p#"$repo/bundles"}" ;;
    "$repo/dsh-mygo"|"$repo/dsh-mygo"/*)        echo "marisa-distro/dsh-mygo${p#"$repo/dsh-mygo"}" ;;
    "$repo/dsh-skill-manager"|"$repo/dsh-skill-manager"/*)
                                                echo "marisa-distro/dsh-skill-manager${p#"$repo/dsh-skill-manager"}" ;;
    "$profile"|"$profile"/*)                    echo ".dsh/profiles/marisa${p#"$profile"}" ;;
    *) return 0 ;;
  esac
}

if (( ! skipBodies )); then
  # NOTE: the original ps1 walks the LIVE repo's harness member-internal
  # node_modules to find symlinks + copy small real entries. On Linux this
  # is both REDUNDANT (the early flatten step already deleted all non-root
  # node_modules from the stage) and DANGEROUS (tar -ch deref follows the
  # circular cordis ↔ cordis-plugin-loader chain into ENAMETOOLONG).
  # Skip it entirely; the staged tree already has all needed content.
  log 'skipping live harness nm walk (early flatten already handled non-root nm)'
  copiedExtra=0

  # profile node_modules is ONE junction to the single root tree.
  record_link '.dsh/profiles/marisa/node_modules' 'marisa-distro/node_modules'

  log 'recording ALL staged symlinks (explicit no-follow walk) ...'
  while IFS= read -r slink; do
    resolved=$(readlink -f "$slink" || true)
    [[ -n $resolved && -d $resolved ]] || continue
    linkRel=${slink#"$stage/"}
    targetRel=''
    case $resolved in
      "$stage"/*) targetRel=${resolved#"$stage/"} ;;
      *) targetRel=$(map_live_to_stage "$resolved") ;;
    esac
    [[ -n $targetRel ]] || continue
    printf '%s\t%s\n' "$linkRel" "$targetRel" >> "$LINKS_TSV.raw"
  done < <(find "$stage" -type l 2>/dev/null)
  [[ -f $LINKS_TSV.raw ]] && cat "$LINKS_TSV.raw" >> "$LINKS_TSV" && rm -f "$LINKS_TSV.raw"

  # dedupe by link path (first wins, like the ps1 HashSet), emit JSON array.
  awk -F'\t' '!seen[$1]++ {printf "%s{\"link\":\"%s\",\"target\":\"%s\"}", sep, $1, $2, sep=", "}' \
    sep='' "$LINKS_TSV" > "$LINKS_TSV.json"
  printf '[%s]\n' "$(cat "$LINKS_TSV.json")" > "$stage/LINKS.json"

  for rl in \
    'marisa-distro/node_modules/@deepseek-ai/schemastery' \
    'marisa-distro/node_modules/@deepseek-ai/dsh-workflow' \
    'marisa-distro/node_modules/@deepseek-ai/dsh-host-webserver' \
    'marisa-distro/node_modules/@deepseek-ai/dsh-host-apiproxy'; do
    grep -qF "\"link\":\"$rl\"" "$stage/LINKS.json" \
      || die "link manifest INCOMPLETE — required root runtime link missing: $rl"
  done
  totalLinks=$(grep -c $'\t' "$LINKS_TSV" || true)
  log "links recorded: $totalLinks (extra real entries copied: ${copiedExtra:-0})"

  # delete EVERY staged symlink after recording (archive carries none).
  # Use -prune on node_modules dirs to prevent find from descending into
  # any surviving circular peer-dep chains. For non-node_modules symlinks,
  # -delete is safe (symlinks are leaf entries).
  rootNm="$stage/marisa-distro/node_modules"
  find "$stage" -type d -name node_modules ! -path "$rootNm" \
    -prune -exec rm -rf {} + 2>/dev/null || true
  find "$stage" -type l -delete 2>/dev/null || true
  remaining=$(find "$stage" -type l 2>/dev/null | wc -l)
  log "symlinks + non-root node_modules deleted (${remaining} unremovable symlinks remaining)"

  # --- runtime dead-weight prune ----------------------------------------------
  log 'pruning runtime dead weight (*.map, test suites) ...'
  dwCount=0
  while IFS= read -r d; do rm -rf "$d"; dwCount=$((dwCount+1)); done \
    < <(find "$stage" -depth -type d \( -name test -o -name tests -o -name __tests__ \) 2>/dev/null)
  while IFS= read -r f; do rm -f "$f"; dwCount=$((dwCount+1)); done \
    < <(find "$stage" -name '*.map' 2>/dev/null)
  log "  pruned $dwCount entries (test dirs + *.map)"

  log 'pruning metadata, docs, and non-runtime dirs ...'
  exCount=0
  while IFS= read -r f; do rm -f "$f"; exCount=$((exCount+1)); done \
    < <(find "$stage" \( -name '*.pdb' -o -name '*.tsbuildinfo' \) 2>/dev/null)
  while IFS= read -r d; do rm -rf "$d"; exCount=$((exCount+1)); done \
    < <(find "$stage" -depth -type d -name '@types' 2>/dev/null)
  for name in .agents .claude .github docs examples scripts website python assets; do
    [[ -e "$stage/marisa-distro/harness/$name" ]] || continue
    rm -rf "$stage/marisa-distro/harness/$name"; exCount=$((exCount+1))
    echo "  pruned harness/$name"
  done
  for area in plugins bundles dsh-mygo; do
    while IFS= read -r d; do rm -rf "$d"; exCount=$((exCount+1)); done \
      < <(find "$stage/marisa-distro/$area" -depth -type d \( -name docs -o -name promo -o -name wechat-submission \) 2>/dev/null)
  done
  [[ -d "$stage/marisa-distro/plugins/dsh-stickers/assets/source" ]] \
    && rm -rf "$stage/marisa-distro/plugins/dsh-stickers/assets/source"
  log "  pruned $exCount metadata/docs entries"

  # dsh-stickers PNG→WebP conversion (sharp linux-x64 binaries survive pruning).
  stickerPlugin="$stage/marisa-distro/plugins/dsh-stickers"
  if [[ -d "$stickerPlugin/assets/stickers" ]]; then
    log 'converting dsh-stickers PNGs to WebP ...'
    node "$repo/desktop/bundle/convert-stickers-webp.mjs" "$stickerPlugin"
  fi

  # --- redundant member-internal node_modules ----------------------------------
  log 'pruning member-internal node_modules (.ignored_*, hoisted dupes) ...'
  intCount=0
  dupeNames='^(node-pty|diff|fflate|chokidar|readdirp)$'
  rootStoreAbs="$nmRoot"
  while IFS= read -r d; do
    dabs=$(readlink -f "$d" 2>/dev/null || echo "$d")
    [[ $dabs == "$rootStoreAbs" || $dabs == "$rootStoreAbs"/* ]] && continue
    while IFS= read -r e; do
      ename=$(basename "$e")
      if [[ $ename == .ignored_* ]]; then
        rm -rf "$e"; intCount=$((intCount+1))
      elif [[ $ename =~ $dupeNames ]]; then
        parentName=$(basename "$(dirname "$e")")
        if [[ $parentName == node_modules ]]; then
          rm -rf "$e"; intCount=$((intCount+1))
        fi
      fi
    done < <(find "$d" -mindepth 1 -maxdepth 1 2>/dev/null)
  done < <(find "$stage" -type d -name node_modules ! -path "$nmRoot" ! -path "$nmRoot/*" 2>/dev/null)
  log "  pruned $intCount entries from member-internal node_modules"

  # pre-pack sanity: root workspace members covered by links OR entities.
  rootLinkCount=$(awk -F'\t' '$1 ~ /^marisa-distro\/node_modules\// {n++} END {print n+0}' "$LINKS_TSV")
  rootEntityCount=$(find "$nmRoot/@deepseek-ai" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l)
  if (( rootLinkCount + rootEntityCount < 10 )); then
    die "suspiciously few root node_modules workspace members (links=$rootLinkCount entities=$rootEntityCount) — refusing to pack"
  fi
  log "  root node_modules workspace coverage: links=$rootLinkCount entities=$rootEntityCount"
fi

# --- tar.zst -------------------------------------------------------------------
log 'tarring + zstd (single stream via tarszst) ...'
mkdir -p "$(dirname "$out")"
(cd "$repo/desktop" && go run ./bundle/tarszst "$stage" "$out")
log "bundle written: $(wc -c <"$out") bytes"

# --- runtime cache write --------------------------------------------------------
if (( ! skipBodies )); then
  mkdir -p "$cacheDir"
  cp -f "$out" "$cachedOut"
  log "runtime cache written: $cachedOut"
fi

rm -f "$LINKS_TSV" "$LINKS_TSV.json" 2>/dev/null || true
log 'make-bundle complete.'
